import { expect, test } from '@playwright/test'

test('首页可以发现并进入姓名贴工具', async ({ page }) => {
  await page.goto('/')
  await expect(page.getByRole('heading', { name: '工具' })).toBeVisible()
  await page.getByRole('link', { name: /学生姓名贴/ }).click()
  await expect(page).toHaveURL(/\/tools\/name-labels$/)
  await expect(page.locator('main h1', { hasText: '标签贴' })).toBeVisible()
})

test('姓名贴工作台支持文本名单和 CSV 列选择', async ({ page }) => {
  await page.goto('/tools/name-labels')
  await page.getByLabel('粘贴或输入名单').fill('林小满\n周知行\n陈安然')
  await page.getByRole('button', { name: '使用这份名单' }).click()
  await page.getByRole('button', { name: /^打印校准：/ }).click()
  await expect(page.getByRole('button', { name: '打印姓名贴' })).toBeEnabled()
  await page.getByRole('button', { name: '单格', exact: true }).click()
  await expect(page.getByRole('button', { name: '单格', exact: true })).toHaveAttribute('aria-pressed', 'true')
  await expect(page.getByText('标签尺寸')).toBeVisible()
  await page.getByRole('button', { name: '整页', exact: true }).click()
  await page.locator('[data-label-cell-id]').first().click()
  await expect(page.getByRole('button', { name: '单格', exact: true })).toHaveAttribute('aria-pressed', 'true')
  await expect(page.getByText('标签尺寸')).toBeVisible()
  await page.getByRole('button', { name: '整页', exact: true }).click()
  await page.getByRole('button', { name: /^导入名单：/ }).click()
  await expect(page.getByText('第 1 / 1 页 · 页面按 mm 排版')).toBeVisible()

  await page.getByRole('button', { name: '清空名单' }).click()
  await expect(page.getByRole('dialog', { name: '清空当前名单？' })).toBeVisible()
  await page.keyboard.press('Escape')
  await expect(page.getByRole('dialog', { name: '清空当前名单？' })).toBeHidden()
  await page.getByRole('button', { name: /^导入名单：/ }).click()

  await page.locator('input[type="file"]').setInputFiles({
    name: '名单.csv',
    mimeType: 'text/csv',
    buffer: Buffer.from('姓名,班级\n李明远,三年级', 'utf8'),
  })
  await expect(page.getByRole('combobox', { name: '第 1 行内容选择' })).toHaveText('姓名')
  await expect(page.getByRole('combobox', { name: '第 2 行内容选择' })).toHaveText('班级')
  await page.getByRole('button', { name: '确认字段选择' }).click()
  await expect(page.getByLabel('当前工作台状态').getByText('1 人')).toBeVisible()
  await expect(page.getByRole('heading', { name: '字段设置' })).toBeVisible()
  const firstLabel = page.locator('.label-text').first()
  await expect(firstLabel.locator('span')).toHaveText(['姓名：李明远', '班级：三年级'])
  await expect(firstLabel.locator('br')).toHaveCount(0)
  await page.getByRole('button', { name: '调整字段' }).click()
  await page.getByRole('switch', { name: '第 1 行是否显示标题' }).click()
  await page.getByRole('switch', { name: '第 2 行是否显示标题' }).click()
  await page.getByRole('button', { name: '更新字段' }).click()
  await expect(firstLabel.locator('span')).toHaveText(['李明远', '三年级'])
})

test('姓名贴工作台在窄屏没有无意横向滚动', async ({ page }) => {
  for (const width of [375, 768, 1024, 1440]) {
    await page.setViewportSize({ width, height: 900 })
    await page.goto('/tools/name-labels')
    await page.getByLabel('粘贴或输入名单').fill('林小满\n周知行\n陈安然')
    await page.getByRole('button', { name: '使用这份名单' }).click()
    const scrollWidth = await page.evaluate(() => document.documentElement.scrollWidth)
    const viewportWidth = await page.evaluate(() => window.innerWidth)
    expect(scrollWidth).toBeLessThanOrEqual(viewportWidth)
  }
  await page.setViewportSize({ width: 667, height: 375 })
  await page.goto('/tools/name-labels')
  await page.getByLabel('粘贴或输入名单').fill('林小满\n周知行\n陈安然')
  await page.getByRole('button', { name: '使用这份名单' }).click()
  expect(await page.evaluate(() => document.documentElement.scrollWidth)).toBeLessThanOrEqual(667)
  await page.setViewportSize({ width: 375, height: 812 })
  await page.goto('/tools/name-labels')
  await page.getByLabel('粘贴或输入名单').fill('林小满\n周知行\n陈安然')
  await page.getByRole('button', { name: '使用这份名单' }).click()
  for (let index = 0; index < 16; index += 1) await page.getByRole('button', { name: '放大预览' }).click()
  await expect(page.getByText('在预览区内滚动查看整张纸。')).toBeVisible()
  const previewOverflow = await page.getByTestId('preview-scroll-container').evaluate((element) => element.scrollWidth > element.clientWidth)
  expect(previewOverflow).toBe(true)
  const documentOverflow = await page.evaluate(() => document.documentElement.scrollWidth > window.innerWidth)
  expect(documentOverflow).toBe(false)
})

test('背景图编辑在移动端提供按钮替代并同步到打印文档', async ({ page }) => {
  await page.setViewportSize({ width: 375, height: 812 })
  await page.goto('/tools/name-labels')
  await page.getByLabel('粘贴或输入名单').fill('林小满\n周知行')
  await page.getByRole('button', { name: '使用这份名单' }).click()
  await page.getByRole('button', { name: /^内容样式：/ }).click()
  await page.getByRole('button', { name: /^背景/ }).click()
  await page.getByRole('tab', { name: '图片背景' }).click()
  await page.locator('input[type="file"]').setInputFiles({ name: 'fixture.png', mimeType: 'image/png', buffer: Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mNk+A8AAQUBAScY42YAAAAASUVORK5CYII=', 'base64') })
  await expect(page.getByText('拖动调整位置')).toBeVisible()
  await page.getByRole('button', { name: '放大背景图片' }).click()
  await page.getByRole('button', { name: '重置背景图片位置' }).click()
  await expect(page.getByTestId('printable-label-document').locator('img')).toHaveCount(2)
  expect(await page.getByTestId('printable-label-document').locator('img').first().getAttribute('src')).toBe(await page.locator('.label-page img').first().getAttribute('src'))
  expect(await page.evaluate(() => document.documentElement.scrollWidth)).toBeLessThanOrEqual(375)
})

test('1000 条名单可以分页并保持打印前页面可用', async ({ page }) => {
  await page.goto('/tools/name-labels')
  await page.getByLabel('粘贴或输入名单').fill(Array.from({ length: 1000 }, (_, index) => '合成学生' + (index + 1)).join('\n'))
  await page.getByRole('button', { name: '使用这份名单' }).click()
  await page.getByRole('button', { name: /^打印校准：/ }).click()
  await expect(page.getByLabel('当前工作台状态').getByText('1000 人')).toBeVisible()
  await expect(page.getByText('第 1 / 20 页 · 页面按 mm 排版')).toBeVisible()
  await expect(page.getByRole('button', { name: '打印姓名贴' })).toBeEnabled()
})
